// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsB3u6DBa5-EvpteRhlrm3mi07JvoQv4',
    appId: '1:103916758019:web:879b04d12817bc50d65a36',
    messagingSenderId: '103916758019',
    projectId: 'my-ecommerce-9556b',
    authDomain: 'my-ecommerce-9556b.firebaseapp.com',
    storageBucket: 'my-ecommerce-9556b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzwDHGyxCmnrQZW2XPhc8noLmLd27oFM',
    appId: '1:103916758019:android:0ce85107a6a983acd65a36',
    messagingSenderId: '103916758019',
    projectId: 'my-ecommerce-9556b',
    storageBucket: 'my-ecommerce-9556b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCsB3u6DBa5-EvpteRhlrm3mi07JvoQv4',
    appId: '1:103916758019:web:da0665c21fbb2674d65a36',
    messagingSenderId: '103916758019',
    projectId: 'my-ecommerce-9556b',
    authDomain: 'my-ecommerce-9556b.firebaseapp.com',
    storageBucket: 'my-ecommerce-9556b.firebasestorage.app',
  );

}